Resources:
  userpoolCloudfrontDistLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: habits-userpoolCloudfrontDist
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: habits-userpoolCloudfrontDist
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - cognito-idp:DescribeUserPoolDomain
                Resource: "*"
